//TodoLists
export const GET_TODO_LISTS = 'GET_TODO_LISTS';
export const TODO_LISTS_ERROR = 'TODO_LISTS_ERROR';
export const SET_CURRENT_DELETED = 'SET_CURRENT_DELETED';
export const CLEAR_CURRENT_DELETED = 'CLEAR_CURRENT_DELETED';
export const SET_CURRENT_VIEWED = 'SET_CURRENT_VIEWED';
export const CLEAR_CURRENT_VIEWED = 'CLEAR_CURRENT_VIEWED';
export const DELETE_TODO_LIST = 'DELETE_TODO_LIST';
export const SEARCH_TODO_LISTS = 'SEARCH_TODO_LISTS';
//TodoListEdit
export const GET_TODO_LIST = 'GET_TODO_LIST';
export const TODO_LIST_EDIT_ERROR = 'TODO_LIST_EDIT_ERROR';
export const SET_CURRENT_EDITED = 'SET_CURRENT_EDITED';
export const CLEAR_CURRENT_EDITED = 'CLEAR_CURRENT_EDITED';
export const DELETE_TODO_LIST_ITEM = 'DELETE_TODO_LIST_ITEM';
export const UPDATE_TODO_LIST_ITEM = 'UPDATE_TODO_LIST_ITEM';
export const COMPLETE_TODO_LIST_ITEM = 'COMPLETE_TODO_LIST_ITEM';
export const ADD_TODO_LIST_ITEM = 'ADD_TODO_LIST_ITEM';
export const ADD_TODO_LIST = 'ADD_TODO_LIST';
export const UPDATE_TODO_LIST = 'UPDATE_TODO_LIST';
export const CLEAR_SAVED_FLAG = 'CLEAR_SAVED_FLAG';
export const TODO_LIST_EDIT_UNLOADED = 'TODO_LIST_EDIT_UNLOADED';
//Shared
export const SET_LOADING = 'SET_LOADING';
export const SHOW_TOAST = 'SHOW_TOAST';
export const CLEAR_TOAST = 'CLEAR_TOAST';
export const SEARCH_LIST = 'SEARCH_LIST';
